easy_admin:
    entities:
        # List the entity class name you want to manage
        Contact:
            class: App\Entity\Contact
        Production:
            class: App\Entity\Production
            list:
                fields:
                    - { property: 'name', type: 'text' }
                    - { property: 'link', type: 'text' }
                    - { property: 'image', template: 'easyAdmin/imageadmin.html.twig' }

#        - App\Entity\Category
#        - App\Entity\User
